[package]
authors = ["eric@harris-braun.com"]
edition = "2021"
name = "integrity"
version = "0.0.1-alpha.1"

[lib]
crate-type = ["cdylib", "rlib"]
name = "integrity"

[dependencies]
#hdk = "=0.0.142"
#hdi = "=0.0.14"
#hdk = { path = "../../../../holochain/crates/hdk" }
#hdi = { path = "../../../../holochain/crates/hdi" }
hdk = { git = "https://github.com/pjkundert/holochain", branch = "must-get-agent-activity-host-fn"}
hdi = { git = "https://github.com/pjkundert/holochain", branch = "must-get-agent-activity-host-fn"}
serde = "1"

[dev-dependencies]
# holochain = { version = "0.0.114", default-features = false, features = ["test_utils"] }
holochain = { git = "https://github.com/pjkundert/holochain", branch = "must-get-agent-activity-host-fn", default-features = false, features = ["test_utils"]}
tokio = { version = "1.20.1", features = ["full"] }
futures = { version = "0.3.21", default-features = false }

